root: true
parserOptions:
  parser: "@typescript-eslint/parser"
  extraFileExtensions: [".vue"]
env:
  browser: true
  es2021: true
  node: true
  "vue/setup-compiler-macros": true
extends:
  - plugin:@typescript-eslint/recommended
  - plugin:vue/vue3-essential
  - prettier
plugins:
  - "@typescript-eslint"
  - vue
globals:
  ga: readonly
  cordova: readonly
  __statics: readonly
  __QUASAR_SSR__: readonly
  __QUASAR_SSR_SERVER__: readonly
  __QUASAR_SSR_CLIENT__: readonly
  __QUASAR_SSR_PWA__: readonly
  process: readonly
  Capacitor: readonly
  chrome: readonly
rules:
  quotes:
    - warn
    - double
    - avoidEscape: true
  no-unused-vars: off
  no-debugger: error
  "@typescript-eslint/no-var-requires": off
